base/urls.py
from django.urls import path, include
from . import views

app_name = 'base'

urlpatterns = [
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
]

development/urls.py
from django.urls import path,include
from . import views

app_name = 'development'

urlpatterns = [
    path('',views.projects,name="projects"),
    path('<int:project_id>/',views.project_view,name="project_view"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('',include('base.urls')),
    path('projects/',include('development.urls')),
]

base/models.py
from django.db import models

# Create your models here.

coding/models.py
from django.db import models
from django.db.models.base import Model
from model_utils import Choices
# Create your models here.
class ProblemTag(models.Model):
    value = models.CharField("Tag name",max_length=200)
    bg_color = models.CharField("Background Color",max_length=6)
    def __str__(self):
        return self.value

class TheoryTopic(models.Model):
    name = models.CharField("Topic",max_length=100)
    def __str__(self):
        return self.name

class TheoryNote(models.Model):
    topic= models.ForeignKey(TheoryTopic,on_delete=models.CASCADE)
    note = models.TextField("Note")
    def __str__(self) -> str:
        return self.topic

class Problem(models.Model):
    statement = models.TextField("Problem Statement")
    tags = models.ManyToManyField(ProblemTag,"Problem_Tags")
    date = models.DateField("problem date")
    link = models.CharField("Link to problem",max_length=200)
    solution = models.TextField("Solution to problem")
    num_attempts = models.IntegerField("No. of attempts")
    STATUS = Choices(('todo', ('todo')), ('repeat', ('repeat')),('done',('done')))
    status = models.CharField(choices=STATUS, default=STATUS.todo, max_length=20)
    def __str__(self) -> str:
        return self.statement

class ProblemNote(models.Model):
    problem = models.ForeignKey(Problem,on_delete=models.CASCADE)
    value = models.TextField("Note")
    def __str__(self):
        return self.value

class Attempt(models.Model):
    problem = models.ForeignKey(Problem,on_delete=models.CASCADE)
    time = models.IntegerField("Time taken")
    def __str__(self) -> str:
        return 'Attempt'+str(Problem.objects.get(id=self.problem.id).num_attempts)

class Score(models.Model):
    attempt = models.ForeignKey(Attempt,on_delete=models.CASCADE)
    SCORECHOICES = Choices((0, 'ZERO',('ZERO')), (1,'ONE', ('ONE')),(2,'TWO',('TWO')),(3,'THREE',('THREE')),(4,'FOUR',('FOUR')),(5,'FIVE',('FIVE')))
    under_30 = models.IntegerField(choices=SCORECHOICES,default=SCORECHOICES.ZERO)
    need_hints = models.IntegerField(choices=SCORECHOICES,default=SCORECHOICES.ZERO)
    was_optimal = models.IntegerField(choices=SCORECHOICES,default=SCORECHOICES.ZERO)
    any_bugs = models.IntegerField(choices=SCORECHOICES,default=SCORECHOICES.ZERO)
    score = models.IntegerField(default=0)
    def save(self,*args, **kwargs):
        self.score = self.under_30+self.need_hints+self.was_optimal+self.any_bugs
        super(Score,self).save(*args, **kwargs)
    def __str__(self):
        return str(Attempt.objects.get(id=self.attempt.id))+' Score '+str(self.score)

development/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class ProjectTag(models.Model):
    # project = models.ForeignKey(Project,on_delete=models.CASCADE)
    value = models.CharField("Tag Name",max_length=50)
    bg_color = models.CharField("Background Color",max_length=6)
    def __str__(self):
        return self.value
class Project(models.Model):
    title = models.CharField("Title",max_length=150)
    link = models.CharField("Link to project",max_length=400,null=True,blank=True)
    deployed_link = models.CharField("Link to deployed project",max_length=400,null=True,blank=True)
    description = models.TextField("Description")
    started_on = models.DateField("Starting date")
    public = models.BooleanField("Public")
    tags = models.ManyToManyField(ProjectTag,"Tags")
    def __str__(self):
        return self.title

base/views.py
from django.shortcuts import render
from development.models import Project,ProjectTag
# Create your views here.
def home(request):
    if request.user.is_staff:
        recent_projects = Project.objects.order_by("started_on")[:3]
    else:
        recent_projects = Project.objects.filter(public=True).order_by("started_on")[:3]
    context = {}
    context['recent_projects'] = recent_projects
    print(context)
    return render(request,'base/index.html',context)

def about(request):
    return render(request,'base/about.html')

def contact(request):
    return render(request,'base/contact.html')

coding/views.py
from django.shortcuts import render

# Create your views here.
    

development/views.py
from development.models import Project, ProjectTag
from django.http.response import HttpResponse
from django.shortcuts import render,get_object_or_404
from .models import *

# Create your views here.
def projects(request):
    if request.user.is_staff:
        project_list = Project.objects.order_by("started_on")[:3]
    else:
        project_list = Project.objects.filter(public=True).order_by("started_on")[:3]
    context = {}
    context['project_list'] = project_list
    print(context)
    return render(request,'development/projects.html',context)

def project_view(request,project_id):
    project = get_object_or_404(Project,id=project_id)
    context = {}
    context['project'] = project
    return render(request,'development/project_view.html',context)

templates/base/about.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} About Me {% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'base/css/index.css' %}">
    <main>
        <center><h1>About Me</h1></center>
        <br>
        <h3 style="text-align: center;">Developer | Finance Enthusiast | Inventor</h3>
        <br>
        <h4>I am a highly motivated person who is willing to learn new things. I always try my best to complete the tasks given to me and as a perfectionist, I can finish it efficiently as possible. I love developing new things that can make changes to my life and of those around me.</h4>
        <br>
        <center><a href="linkedin.com/in/md-manzer-alam-0ba00280">My Linkedin</a></center>
        <br>
    </main>
    <style>
        a{
            color: skyblue;
        }
    </style>
{% endblock %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <script src="https://kit.fontawesome.com/3fffe96fcb.js" crossorigin="anonymous"></script>
</head>
<body>
    {% include 'base/snippets/navigation.html' %}
    {% block content %}
    {% endblock %}
    {% include 'base/snippets/footer.html' %}
</body>
</html>

templates/base/contact.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Contact {% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'base/css/index.css' %}">
    <main>
        <center><h1>Contact</h1></center>
        <br>
        <h3>Feel free to contact me at <a href="mailto:18preneur@gmail.com">18preneur@gmail.com</a> or contact me from <a href="https://sherlock6147.github.io/contact.html">here</a></h3>
    </main>
    <style>
        a{
            color: skyblue;
        }
    </style>
{% endblock %}

templates/base/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Home {% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'base/css/index.css' %}">
    <section class="header">
        <ul>
            <li class="holder">
                <div class="img-container">
                    <img src="{% static 'base/media/welcome.svg' %}" alt="welcome-img">
                </div>
            </li>
            <li class="holder">
                <div class="card" id="newsletter_signup">
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                            <h1>Its better to sweat in practice than bleed in war</h1>
                            <br>
                            <h3>Keep coding, Keep learning!</h3>
                            <br>
                            <center>
                                <li>
                                    <a href="#" class="signup-btn">Practice</a>
                                </li>
                            </center>
                        {% else %}
                            <h1>I am a passionate developer and tech enthusast.</h1>
                            <br>
                            <h3>See my coding journey.</h3>
                            <br>
                            <center>
                                <li>
                                    <a href="#" class="signup-btn">Problems</a>
                                </li>
                                <br>
                                <li>
                                    <a href="#" class="signup-btn">Projects</a>
                                </li>
                            </center>
                        {% endif %}
                    {% else %}
                        <h1>I am a passionate developer and tech enthusast.</h1>
                        <br>
                        <h3>Signup to my coding journey newsletter below to stay updated with my coding journey.</h3>
                        <br>
                        <center>
                            <li>
                                <a href="{% url 'account_signup' %}" class="signup-btn">Signup</a>
                            </li>
                                <br>
                            <li>
                                <a title="Google" class="socialaccount_provider google signup-btn" href="/accounts/google/login/?process=login">Signup with Google</a>
                            </li>
                        </center>
                    {% endif %}
                </div>
            </li>
        </ul>
    </section>
    <section class="recent-projects">
        <h2>Recent Projects</h2>
        {% if recent_projects %}
            <div class="projects">
                {% for project in recent_projects %}
                    <div class="card">
                        <h3>{{project.title}}</h3>
                        <h4>Start Date: {{project.started_on}}</h4>
                        <br>
                        <h4>{{project.description|truncatechars:40}} <a href="{% url 'development:project_view' project.id %}" class="read_more">Read more.</a></h4>
                        <ul class="tags_holder">
                            {% for tag in project.tags.all %}
                                <li style="background-color: {{tag.bg_color}};">{{tag.value}}</li>
                            {% endfor %}
                        </ul>
                        <div class="project_link">
                            <a href="{{project.link}}">Github Repo <i class="fab fa-github"></i></a>
                        </div>
                    </div>    
                {% endfor %}
            </div>
        {% else %}
            <h3>No Projects Added Yet</h3>
        {% endif %}
    </section>
{% endblock %}

templates/base/snippets/navigation.html
{% load static %}
<link rel="stylesheet" href="{% static 'base/css/snippets/navigation.css' %}">
<section class="nav-section top">
    <h2 id="logo">My Coding Journey</h2>
    <ul class="links" id="large">
        <li class="link-holder"><a href="{% url 'base:home' %}">Home</a></li>
        <!-- <li class="link-holder"><a href="#">Problems</a></li> -->
        <li class="link-holder"><a href="{% url 'development:projects' %}">Projects</a></li>
        {% if user.is_staff %}
            <!-- <li class="link-holder"><a href="#">Practice</a></li> -->
            <!-- <li class="link-holder"><a href="#">Notes</a></li> -->
        {% endif %}
        <li class="link-holder"><a href="{% url 'base:about' %}">About</a></li>
        <li class="link-holder"><a href="{% url 'base:contact' %}">Contact</a></li>
        {% if user.is_authenticated %}
            <li class="link-holder special"><a href="{% url 'account_logout' %}">Logout</a></li>
        {% else %}
            <li class="link-holder special"><a href="{% url 'account_login' %}">Login</a></li>
        {% endif %}
    </ul>
    <button id="hamburger-btn" onclick="toggleMenu()" >
        <div class="rect"></div>
        <div class="rect"></div>
        <div class="rect"></div>
    </button>
</section>
<div class="small-nav top">
    <ul class="links" id="small">
        <li class="link-holder"><a href="{% url 'base:home' %}">Home</a></li>
        <!-- <li class="link-holder"><a href="#">Problems</a></li> -->
        <li class="link-holder"><a href="{% url 'development:projects' %}">Projects</a></li>
        {% if user.is_staff %}
            <!-- <li class="link-holder"><a href="#">Practice</a></li> -->
            <!-- <li class="link-holder"><a href="#">Notes</a></li> -->
        {% endif %}
        <li class="link-holder"><a href="{% url 'base:about' %}">About</a></li>
        <li class="link-holder"><a href="{% url 'base:contact' %}">Contact</a></li>
        {% if user.is_authenticated %}
            <li class="link-holder special"><a href="{% url 'account_logout' %}">Logout</a></li>
        {% else %}
            <li class="link-holder special"><a href="{% url 'account_login' %}">Login</a></li>
        {% endif %}
    </ul>
</div>
<script>
    function toggleMenu(){
        let menu = document.getElementById("small");
        menu.classList.toggle('visible');
    }
</script>

templates/development/project_view.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Projects {% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'development/css/project_view.css' %}">
    <main>
        <h2 id="title">{{project.title}}</h2>
        <ul class="tags_holder">
            {% for tag in project.tags.all %}
                <li style="background-color: {{tag.bg_color}};">{{tag.value}}</li>
            {% endfor %}
        </ul>
        <br>
        <h3>Commenced on {{project.started_on}}</h3>
        <br>
        <p>{{project.description}}</p>
        <br>
        {% if project.link %}
            <small><a href="{{project.link}}">Github Repo <i class="fab fa-github"></i></a></small>
        {% endif %}
        <br>
        {% if project.deployed_link %}
            <small><a href="{{project.deployed_link}}">Link to deployed project <i class="fas fa-rocket"></i></a></small>
        {% endif %}
        <br>
    </main>
{% endblock %}

templates/development/projects.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Projects {% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'development/css/projects.css' %}">
    <main>
        <center><h2>Projects</h2></center>
        {% if project_list %}
        <div class="projects">
            {% for project in project_list %}
                <div class="card">
                    <h3>{{project.title}}</h3>
                    <h4>Start Date: {{project.started_on}}</h4>
                    <br>
                    <h4>{{project.description|truncatechars:40}} <a href="{% url 'development:project_view' project.id %}" class="read_more">Read more.</a></h4>
                    <ul class="tags_holder">
                        {% for tag in project.tags.all %}
                            <li style="background-color: {{tag.bg_color}};">{{tag.value}}</li>
                        {% endfor %}
                    </ul>
                    <div class="project_link">
                        <a href="{{project.link}}">Github Repo <i class="fab fa-github"></i></a>
                    </div>
                </div>    
            {% endfor %}
        {% else %}
            <h3>No projects added! Build some now!</h3>
        {% endif %}
    </main>
{% endblock %}